--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "CINEPHILE"."MEMBER_TBL" cascade constraints;
DROP TABLE "CINEPHILE"."NOTICE_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "CINEPHILE"."MEMBER_TBL" 
   (	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_PHONE" VARCHAR2(11 BYTE), 
	"ENROLL_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "CINEPHILE"."NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(100 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(3000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(20 BYTE), 
	"NOTICE_DATE" DATE DEFAULT SYSDATE, 
	"VIEW_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CINEPHILE.MEMBER_TBL
SET DEFINE OFF;
Insert into CINEPHILE.MEMBER_TBL (MEMBER_NAME,MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_PHONE,ENROLL_DATE) values ('일용자','khuser01','pass01','khuser01@naver.com','01045687856',to_timestamp('23/08/01 17:22:07.613000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CINEPHILE.MEMBER_TBL (MEMBER_NAME,MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_PHONE,ENROLL_DATE) values ('이용자','khuser02','pass02','khuser02@naver.com','01065325568',to_timestamp('23/08/07 10:33:53.762000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into CINEPHILE.NOTICE_TBL
SET DEFINE OFF;
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (3,'안녕하세요','반가워요','admin',to_date('23/08/01','RR/MM/DD'),null);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (4,'테스트작성','안녕하세요','admin',to_date('23/08/01','RR/MM/DD'),null);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (6,'중앙방역대책본부의 실내 마스크 착용 의무 추가조정','중앙방역대책본부의 실내 마스크 착용 의무 추가조정(6.1시행)등 방역상황 변화에 따라 

 

''코로나19관련 훈련생 출석 처리방법 변경''됨을 안내받아 공유드립니다.

 

 

변경 전(~23.05.31)

 출석 인정 

  - 감염 여부 검사 시: 검사일 출석인정 가능 (음성이여도)

  - 확진자: 격리에 필요한 기간 출석인정 가능

 

 

변경 후(23.06.01~)

 출석 인정 

  - 감염 여부 검사 시: 출석 인정 불가

  - 확진자: 격리권고 기간(5일) 출석인정 가능','admin',to_date('23/08/02','RR/MM/DD'),null);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (102,'공지사항(95)','공지사항입니다.(95)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (8,'공지사항(1)','공지사항입니다.(1)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (9,'공지사항(2)','공지사항입니다.(2)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (10,'공지사항(3)','공지사항입니다.(3)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (11,'공지사항(4)','공지사항입니다.(4)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (12,'공지사항(5)','공지사항입니다.(5)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (13,'공지사항(6)','공지사항입니다.(6)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (14,'공지사항(7)','공지사항입니다.(7)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (15,'공지사항(8)','공지사항입니다.(8)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (16,'공지사항(9)','공지사항입니다.(9)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (17,'공지사항(10)','공지사항입니다.(10)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (18,'공지사항(11)','공지사항입니다.(11)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (19,'공지사항(12)','공지사항입니다.(12)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (20,'공지사항(13)','공지사항입니다.(13)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (21,'공지사항(14)','공지사항입니다.(14)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (22,'공지사항(15)','공지사항입니다.(15)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (23,'공지사항(16)','공지사항입니다.(16)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (24,'공지사항(17)','공지사항입니다.(17)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (25,'공지사항(18)','공지사항입니다.(18)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (26,'공지사항(19)','공지사항입니다.(19)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (27,'공지사항(20)','공지사항입니다.(20)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (28,'공지사항(21)','공지사항입니다.(21)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (29,'공지사항(22)','공지사항입니다.(22)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (30,'공지사항(23)','공지사항입니다.(23)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (31,'공지사항(24)','공지사항입니다.(24)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (32,'공지사항(25)','공지사항입니다.(25)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (33,'공지사항(26)','공지사항입니다.(26)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (34,'공지사항(27)','공지사항입니다.(27)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (35,'공지사항(28)','공지사항입니다.(28)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (36,'공지사항(29)','공지사항입니다.(29)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (37,'공지사항(30)','공지사항입니다.(30)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (38,'공지사항(31)','공지사항입니다.(31)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (39,'공지사항(32)','공지사항입니다.(32)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (40,'공지사항(33)','공지사항입니다.(33)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (41,'공지사항(34)','공지사항입니다.(34)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (42,'공지사항(35)','공지사항입니다.(35)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (43,'공지사항(36)','공지사항입니다.(36)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (44,'공지사항(37)','공지사항입니다.(37)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (45,'공지사항(38)','공지사항입니다.(38)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (46,'공지사항(39)','공지사항입니다.(39)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (47,'공지사항(40)','공지사항입니다.(40)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (48,'공지사항(41)','공지사항입니다.(41)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (49,'공지사항(42)','공지사항입니다.(42)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (50,'공지사항(43)','공지사항입니다.(43)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (51,'공지사항(44)','공지사항입니다.(44)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (52,'공지사항(45)','공지사항입니다.(45)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (53,'공지사항(46)','공지사항입니다.(46)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (54,'공지사항(47)','공지사항입니다.(47)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (55,'공지사항(48)','공지사항입니다.(48)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (56,'공지사항(49)','공지사항입니다.(49)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (57,'공지사항(50)','공지사항입니다.(50)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (58,'공지사항(51)','공지사항입니다.(51)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (59,'공지사항(52)','공지사항입니다.(52)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (60,'공지사항(53)','공지사항입니다.(53)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (61,'공지사항(54)','공지사항입니다.(54)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (62,'공지사항(55)','공지사항입니다.(55)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (63,'공지사항(56)','공지사항입니다.(56)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (64,'공지사항(57)','공지사항입니다.(57)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (65,'공지사항(58)','공지사항입니다.(58)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (66,'공지사항(59)','공지사항입니다.(59)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (67,'공지사항(60)','공지사항입니다.(60)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (68,'공지사항(61)','공지사항입니다.(61)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (69,'공지사항(62)','공지사항입니다.(62)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (70,'공지사항(63)','공지사항입니다.(63)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (71,'공지사항(64)','공지사항입니다.(64)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (72,'공지사항(65)','공지사항입니다.(65)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (73,'공지사항(66)','공지사항입니다.(66)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (74,'공지사항(67)','공지사항입니다.(67)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (75,'공지사항(68)','공지사항입니다.(68)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (76,'공지사항(69)','공지사항입니다.(69)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (77,'공지사항(70)','공지사항입니다.(70)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (78,'공지사항(71)','공지사항입니다.(71)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (79,'공지사항(72)','공지사항입니다.(72)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (80,'공지사항(73)','공지사항입니다.(73)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (81,'공지사항(74)','공지사항입니다.(74)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (82,'공지사항(75)','공지사항입니다.(75)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (83,'공지사항(76)','공지사항입니다.(76)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (84,'공지사항(77)','공지사항입니다.(77)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (85,'공지사항(78)','공지사항입니다.(78)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (86,'공지사항(79)','공지사항입니다.(79)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (87,'공지사항(80)','공지사항입니다.(80)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (88,'공지사항(81)','공지사항입니다.(81)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (89,'공지사항(82)','공지사항입니다.(82)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (90,'공지사항(83)','공지사항입니다.(83)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (91,'공지사항(84)','공지사항입니다.(84)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (92,'공지사항(85)','공지사항입니다.(85)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (93,'공지사항(86)','공지사항입니다.(86)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (94,'공지사항(87)','공지사항입니다.(87)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (95,'공지사항(88)','공지사항입니다.(88)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (96,'공지사항(89)','공지사항입니다.(89)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (97,'공지사항(90)','공지사항입니다.(90)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (98,'공지사항(91)','공지사항입니다.(91)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (99,'공지사항(92)','공지사항입니다.(92)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (100,'공지사항(93)','공지사항입니다.(93)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (101,'공지사항(94)','공지사항입니다.(94)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (103,'공지사항(96)','공지사항입니다.(96)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (104,'공지사항(97)','공지사항입니다.(97)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (105,'공지사항(98)','공지사항입니다.(98)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (106,'공지사항(99)','공지사항입니다.(99)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (107,'공지사항(100)','공지사항입니다.(100)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (108,'공지사항(101)','공지사항입니다.(101)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (109,'공지사항(102)','공지사항입니다.(102)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (110,'공지사항(103)','공지사항입니다.(103)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (111,'공지사항(104)','공지사항입니다.(104)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (112,'공지사항(105)','공지사항입니다.(105)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (113,'공지사항(106)','공지사항입니다.(106)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (114,'공지사항(107)','공지사항입니다.(107)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (115,'공지사항(108)','공지사항입니다.(108)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (116,'공지사항(109)','공지사항입니다.(109)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (117,'공지사항(110)','공지사항입니다.(110)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (118,'공지사항(111)','공지사항입니다.(111)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (119,'공지사항(112)','공지사항입니다.(112)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (120,'공지사항(113)','공지사항입니다.(113)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (121,'공지사항(114)','공지사항입니다.(114)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (122,'공지사항(115)','공지사항입니다.(115)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (123,'공지사항(116)','공지사항입니다.(116)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (124,'공지사항(117)','공지사항입니다.(117)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (125,'공지사항(118)','공지사항입니다.(118)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (126,'공지사항(119)','공지사항입니다.(119)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (127,'공지사항(120)','공지사항입니다.(120)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (128,'공지사항(121)','공지사항입니다.(121)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (129,'공지사항(122)','공지사항입니다.(122)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (130,'공지사항(123)','공지사항입니다.(123)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (131,'공지사항(124)','공지사항입니다.(124)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (132,'공지사항(125)','공지사항입니다.(125)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (133,'공지사항(126)','공지사항입니다.(126)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (134,'공지사항(127)','공지사항입니다.(127)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (135,'공지사항(128)','공지사항입니다.(128)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (136,'공지사항(129)','공지사항입니다.(129)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (137,'공지사항(130)','공지사항입니다.(130)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (138,'공지사항(131)','공지사항입니다.(131)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (139,'공지사항(132)','공지사항입니다.(132)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (140,'공지사항(133)','공지사항입니다.(133)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (141,'공지사항(134)','공지사항입니다.(134)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (142,'공지사항(135)','공지사항입니다.(135)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (143,'공지사항(136)','공지사항입니다.(136)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (144,'공지사항(137)','공지사항입니다.(137)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (145,'공지사항(138)','공지사항입니다.(138)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (146,'공지사항(139)','공지사항입니다.(139)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (147,'공지사항(140)','공지사항입니다.(140)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (148,'공지사항(141)','공지사항입니다.(141)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (149,'공지사항(142)','공지사항입니다.(142)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (150,'공지사항(143)','공지사항입니다.(143)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (151,'공지사항(144)','공지사항입니다.(144)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (152,'공지사항(145)','공지사항입니다.(145)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (153,'공지사항(146)','공지사항입니다.(146)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (154,'공지사항(147)','공지사항입니다.(147)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (155,'공지사항(148)','공지사항입니다.(148)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (156,'공지사항(149)','공지사항입니다.(149)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (157,'공지사항(150)','공지사항입니다.(150)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (158,'공지사항(151)','공지사항입니다.(151)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (159,'공지사항(152)','공지사항입니다.(152)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (160,'공지사항(153)','공지사항입니다.(153)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (161,'공지사항(154)','공지사항입니다.(154)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (162,'공지사항(155)','공지사항입니다.(155)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (163,'공지사항(156)','공지사항입니다.(156)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (164,'공지사항(157)','공지사항입니다.(157)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (165,'공지사항(158)','공지사항입니다.(158)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (166,'공지사항(159)','공지사항입니다.(159)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (167,'공지사항(160)','공지사항입니다.(160)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (168,'공지사항(161)','공지사항입니다.(161)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (169,'공지사항(162)','공지사항입니다.(162)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (170,'공지사항(163)','공지사항입니다.(163)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (171,'공지사항(164)','공지사항입니다.(164)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (172,'공지사항(165)','공지사항입니다.(165)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (173,'공지사항(166)','공지사항입니다.(166)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (174,'공지사항(167)','공지사항입니다.(167)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (175,'공지사항(168)','공지사항입니다.(168)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (176,'공지사항(169)','공지사항입니다.(169)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (177,'공지사항(170)','공지사항입니다.(170)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (178,'공지사항(171)','공지사항입니다.(171)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (179,'공지사항(172)','공지사항입니다.(172)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (180,'공지사항(173)','공지사항입니다.(173)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (181,'공지사항(174)','공지사항입니다.(174)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (182,'공지사항(175)','공지사항입니다.(175)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (183,'공지사항(176)','공지사항입니다.(176)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (184,'공지사항(177)','공지사항입니다.(177)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (185,'공지사항(178)','공지사항입니다.(178)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (186,'공지사항(179)','공지사항입니다.(179)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (187,'공지사항(180)','공지사항입니다.(180)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (188,'공지사항(181)','공지사항입니다.(181)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (189,'공지사항(182)','공지사항입니다.(182)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (190,'공지사항(183)','공지사항입니다.(183)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (191,'공지사항(184)','공지사항입니다.(184)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (192,'공지사항(185)','공지사항입니다.(185)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (193,'공지사항(186)','공지사항입니다.(186)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (194,'공지사항(187)','공지사항입니다.(187)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (195,'공지사항(188)','공지사항입니다.(188)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (196,'공지사항(189)','공지사항입니다.(189)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (197,'공지사항(190)','공지사항입니다.(190)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (198,'공지사항(191)','공지사항입니다.(191)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (199,'공지사항(192)','공지사항입니다.(192)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (200,'공지사항(193)','공지사항입니다.(193)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (201,'공지사항(194)','공지사항입니다.(194)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (202,'공지사항(195)','공지사항입니다.(195)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (203,'공지사항(196)','공지사항입니다.(196)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (204,'공지사항(197)','공지사항입니다.(197)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (205,'공지사항(198)','공지사항입니다.(198)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (206,'공지사항(199)','공지사항입니다.(199)','admin',to_date('23/08/07','RR/MM/DD'),0);
Insert into CINEPHILE.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE,VIEW_COUNT) values (207,'공지사항(200)','공지사항입니다.(200)','admin',to_date('23/08/07','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007212
--------------------------------------------------------

  CREATE UNIQUE INDEX "CINEPHILE"."SYS_C007212" ON "CINEPHILE"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "CINEPHILE"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CINEPHILE"."MEMBER_TBL" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."MEMBER_TBL" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."MEMBER_TBL" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "CINEPHILE"."NOTICE_TBL" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."NOTICE_TBL" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."NOTICE_TBL" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CINEPHILE"."NOTICE_TBL" MODIFY ("NOTICE_NO" NOT NULL ENABLE);
